I added the search html file but couldn't get any of the gs code to work
chihacknight/books-to-women-in-prison pull request #10
Opened 2019-09-18 02:22 UTC by biniona

2019-09-18 22:48 UTC, miekof requested changes
Can you also include Issue ID's in the git log? 
I can sow you how next Tuesday.

2019-09-18 22:48 UTC, miekof commented on Search.html
> +        Logger.log("HELLO WORLD");
Remove this log or make it more meaningful.

2019-09-18 22:48 UTC, miekof commented on Search.html
> +        ISBN: <input type="search" name="ISBN"> <br>
Can you update the input fields based on the design spec?

2019-09-18 22:48 UTC, miekof commented on Code.gs
> +//prase list items to comma separated string
this function is already in the master branch. Let's figure out how to rebase the code next Tuesday.

2019-09-19 13:29 UTC, biniona commented
Sounds good! I don't think I have much time this upcoming week to make the
requested changes, but I am looking forward to going back and reworking the
code next Tuesday or if i find time.

Best, Alek

On Wed, Sep 18, 2019 at 5:48 PM Mieko Furuhashi <notifications@github.com>
wrote:

> *@miekof* requested changes on this pull request.
>
> Can you also include Issue ID's in the git log?
> I can sow you how next Tuesday.
> ------------------------------
>
> In Search.html
> <https://github.com/chihacknight/books-to-women-in-prison/pull/10#discussion_r325924386>
> :
>
> > @@ -0,0 +1,26 @@
> +<!DOCTYPE html>
> +<html>
> +  <head>
> +    <base target="_top">
> +    <script>
> +    function handleFormSubmit(formObject) {
> +        Logger.log("HELLO WORLD");
>
> Remove this log or make it more meaningful.
> ------------------------------
>
> In Search.html
> <https://github.com/chihacknight/books-to-women-in-prison/pull/10#discussion_r325924572>
> :
>
> > @@ -0,0 +1,26 @@
> +<!DOCTYPE html>
> +<html>
> +  <head>
> +    <base target="_top">
> +    <script>
> +    function handleFormSubmit(formObject) {
> +        Logger.log("HELLO WORLD");
> +        google.script.run.withSuccessHandler(display).processSearch(formObject);
> +    }
> +    </script>
> +  </head>
> +
> +  <body>
> +    <form onsubmit="handleFormSubmit(this)">
> +        ISBN: <input type="search" name="ISBN"> <br>
>
> Can you update the input fields based on the design spec?
> ------------------------------
>
> In Code.gs
> <https://github.com/chihacknight/books-to-women-in-prison/pull/10#discussion_r325924745>
> :
>
> > @@ -94,6 +110,18 @@ function getBookInfoWithIsbn(isbn){
>  function parseMyList(list) {
>  }
>
> +//prase list items to comma separated string
>
> this function is already in the master branch. Let's figure out how to
> rebase the code next Tuesday.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chihacknight/books-to-women-in-prison/pull/10?email_source=notifications&email_token=AEAC23QYBCOQGGSNJ7FMUTTQKKV33A5CNFSM4IXYDJK2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCFGL4XI#pullrequestreview-290242141>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEAC23QEJQR3ZG2WJD4VVADQKKV33ANCNFSM4IXYDJKQ>
> .
>

2019-10-02 01:02 UTC, merged